/**:
  ros__parameters:
    planning_scene_monitor_options:
      name: "robot_skills_planning_scene_monitor"
      robot_description: "robot_description"
      joint_state_topic: "/joint_states"
      attached_collision_object_topic: "/attached_collision_object"
      publish_planning_scene_topic: "/planning_scene"
      monitored_planning_scene_topic: "monitored_planning_scene"
      wait_for_initial_state_timeout: 25.0

    octomap_resolution: 0.1

    planning_pipelines:
      # Load all 4 planning pipelines
      pipeline_names: ["ompl", "pilz_industrial_motion_planner", "chomp", "stomp"]

    ompl:
      planning_plugin: ompl_interface/OMPLPlanner
      planning_plugins:
        - ompl_interface/OMPLPlanner
      request_adapters:
        - default_planning_request_adapters/ResolveConstraintFrames
        - default_planning_request_adapters/ValidateWorkspaceBounds
        - default_planning_request_adapters/CheckStartStateCollision
      response_adapters:
        - default_planning_response_adapters/AddTimeOptimalParameterization
        - default_planning_response_adapters/ValidateSolution
      default_workspace_bounds: 2.0
      planning_time: 5.0
      max_planning_threads: 8

      left_arm:
        planner_configs:
          - RRTConnectkConfigDefault
          - LBKPIECEkConfigDefault
          - RRTstarkConfigDefault
          - TRRTkConfigDefault
      right_arm:
        planner_configs:
          - RRTConnectkConfigDefault
          - LBKPIECEkConfigDefault
          - RRTstarkConfigDefault
          - TRRTkConfigDefault
      both_arms:
        planner_configs:
          - RRTConnectkConfigDefault
          - LBKPIECEkConfigDefault
          - RRTstarkConfigDefault
          - TRRTkConfigDefault

      planner_configs:
        RRTConnectkConfigDefault:
          type: geometric::RRTConnect
          range: 0.5
          longest_valid_segment_fraction: 0.01
        LBKPIECEkConfigDefault:
          type: geometric::LBKPIECE
          range: 0.5
          longest_valid_segment_fraction: 0.01
        RRTstarkConfigDefault:
          type: geometric::RRTstar
          range: 0.5
          goal_bias: 0.05
          delay_collision_checking: 1
        TRRTkConfigDefault:
          type: geometric::TRRT
          range: 0.5
          goal_bias: 0.05
          delay_collision_checking: 1

    pilz_industrial_motion_planner:
      planning_plugin: pilz_industrial_motion_planner/CommandPlanner
      planning_plugins:
        - pilz_industrial_motion_planner/CommandPlanner
      request_adapters:
        - default_planning_request_adapters/ResolveConstraintFrames
        - default_planning_request_adapters/ValidateWorkspaceBounds
      response_adapters:
        - default_planning_response_adapters/ValidateSolution

    chomp:
      planning_plugin: chomp_interface/CHOMPPlanner
      planning_plugins:
        - chomp_interface/CHOMPPlanner
      request_adapters:
        - default_planning_request_adapters/ResolveConstraintFrames
        - default_planning_request_adapters/ValidateWorkspaceBounds
      response_adapters:
        - default_planning_response_adapters/ValidateSolution

    stomp:
      planning_plugin: stomp_moveit/StompPlanner
      planning_plugins:
        - stomp_moveit/StompPlanner
      request_adapters:
        - default_planning_request_adapters/ResolveConstraintFrames
        - default_planning_request_adapters/ValidateWorkspaceBounds
      response_adapters:
        - default_planning_response_adapters/ValidateSolution
