#include "sequence_executor/hand_api_client.hpp"

#include <chrono>
#include <condition_variable>
#include <cstring>
#include <sstream>

#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <unistd.h>

namespace sequence_executor {

namespace {

constexpr auto kConnectTimeout = std::chrono::seconds(3);
constexpr auto kDrainPeriod = std::chrono::milliseconds(50);
constexpr std::size_t kReadBuffer = 8192;

// The hand API answers `{"success": true, ...}` or
// `{"success": false, "message": "..."}`. Rather than pull in a JSON parser
// for two fields, look for the literal - the payload is machine-generated by
// Flask's jsonify and its shape does not vary.
bool bodySaysSuccess(const std::string& body)
{
  return body.find("\"success\": true") != std::string::npos ||
         body.find("\"success\":true") != std::string::npos;
}

std::string extractMessage(const std::string& body)
{
  for (const char* key : {"\"message\": \"", "\"message\":\""}) {
    const auto start = body.find(key);
    if (start == std::string::npos) {
      continue;
    }
    const auto from = start + std::strlen(key);
    const auto end = body.find('"', from);
    if (end != std::string::npos) {
      return body.substr(from, end - from);
    }
  }
  return body.substr(0, 200);
}

}  // namespace

HandApiClient::HandApiClient(const rclcpp::Node::SharedPtr& node, const std::string& host, int port)
  : node_(node), host_(host), port_(port), logger_(node->get_logger())
{
  worker_ = std::thread([this]() {
    for (;;) {
      std::function<void()> job;
      {
        std::unique_lock<std::mutex> lock(mutex_);
        cv_.wait(lock, [this]() { return stop_ || !pending_.empty(); });
        if (stop_ && pending_.empty()) {
          return;
        }
        job = std::move(pending_.front());
        pending_.pop_front();
      }
      job();
    }
  });

  completion_timer_ =
    node_->create_wall_timer(kDrainPeriod, [this]() { drainCompletions(); });
}

HandApiClient::~HandApiClient()
{
  {
    std::lock_guard<std::mutex> lock(mutex_);
    stop_ = true;
  }
  cv_.notify_all();
  if (worker_.joinable()) {
    worker_.join();
  }
}

void HandApiClient::enqueue(std::function<void()> work, ResultCallback callback)
{
  {
    std::lock_guard<std::mutex> lock(mutex_);
    pending_.push_back(std::move(work));
  }
  (void)callback;   // the work closure already owns it
  cv_.notify_one();
}

void HandApiClient::drainCompletions()
{
  // Copy out under the lock, then invoke outside it: a callback re-entering
  // this client (the next step being another hand move) would otherwise
  // deadlock on the same mutex.
  std::deque<std::pair<ResultCallback, std::pair<bool, std::string>>> ready;
  {
    std::lock_guard<std::mutex> lock(mutex_);
    ready.swap(completed_);
  }
  for (auto& entry : ready) {
    if (entry.first) {
      entry.first(entry.second.first, entry.second.second);
    }
  }
}

void HandApiClient::moveFingers(const std::vector<FingerTarget>& targets, ResultCallback callback)
{
  if (targets.empty()) {
    // Nothing to do, but the caller still expects exactly one callback.
    std::lock_guard<std::mutex> lock(mutex_);
    completed_.push_back({std::move(callback), {true, ""}});
    return;
  }

  auto work = [this, targets, callback]() {
    bool ok = true;
    std::string message;

    // The API moves one finger per call. Group the targets by finger so a
    // finger with both motors set goes out as a single request - the board
    // then moves them together instead of twitching one and then the other.
    for (int finger = 1; finger <= 4 && ok; ++finger) {
      std::ostringstream body;
      bool any = false;
      body << "{\"finger\": " << finger;
      for (const auto& target : targets) {
        if (target.finger != finger) {
          continue;
        }
        body << ", \"m" << target.motor << "\": " << static_cast<int>(target.angle);
        any = true;
      }
      body << "}";
      if (!any) {
        continue;
      }

      std::string response;
      std::string error;
      if (!request("POST", "/api/hand/move", body.str(), response, error)) {
        ok = false;
        message = error;
      } else if (!bodySaysSuccess(response)) {
        ok = false;
        message = "hand API refused finger " + std::to_string(finger) + ": " +
                  extractMessage(response);
      }
    }

    std::lock_guard<std::mutex> lock(mutex_);
    completed_.push_back({callback, {ok, message}});
  };

  enqueue(std::move(work), callback);
}

void HandApiClient::home(int finger, ResultCallback callback)
{
  auto work = [this, finger, callback]() {
    const std::string body = (finger >= 1 && finger <= 4)
                               ? "{\"finger\": " + std::to_string(finger) + "}"
                               : "{}";
    std::string response;
    std::string error;
    bool ok = request("POST", "/api/hand/home", body, response, error);
    if (ok && !bodySaysSuccess(response)) {
      ok = false;
      error = "hand API refused home: " + extractMessage(response);
    }

    std::lock_guard<std::mutex> lock(mutex_);
    completed_.push_back({callback, {ok, error}});
  };

  enqueue(std::move(work), callback);
}

bool HandApiClient::probe(std::string& detail)
{
  std::string response;
  std::string error;
  if (!request("GET", "/api/health", "", response, error)) {
    board_reachable_ = false;
    detail = "hand API at " + host_ + ":" + std::to_string(port_) + " is not answering (" +
             error + ")";
    return false;
  }

  board_reachable_ = response.find("\"board_reachable\": true") != std::string::npos ||
                     response.find("\"board_reachable\":true") != std::string::npos;
  detail = board_reachable_
             ? "hand board reachable"
             : "hand API is up but the board is not reachable - check the Ethernet "
               "cable on end0 (board is 192.168.10.100, host is 192.168.10.1/24)";
  return board_reachable_;
}

bool HandApiClient::request(const std::string& method, const std::string& path,
                            const std::string& body, std::string& response, std::string& error)
{
  const int fd = ::socket(AF_INET, SOCK_STREAM, 0);
  if (fd < 0) {
    error = "could not open a socket";
    return false;
  }

  struct timeval tv{};
  tv.tv_sec = std::chrono::duration_cast<std::chrono::seconds>(kConnectTimeout).count();
  ::setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));
  ::setsockopt(fd, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof(tv));

  struct sockaddr_in addr{};
  addr.sin_family = AF_INET;
  addr.sin_port = htons(static_cast<uint16_t>(port_));
  if (::inet_pton(AF_INET, host_.c_str(), &addr.sin_addr) != 1) {
    ::close(fd);
    error = "'" + host_ + "' is not a numeric IPv4 address";
    return false;
  }

  if (::connect(fd, reinterpret_cast<struct sockaddr*>(&addr), sizeof(addr)) != 0) {
    ::close(fd);
    error = "could not connect to " + host_ + ":" + std::to_string(port_) +
            " - is hand-api running?";
    return false;
  }

  std::ostringstream request_text;
  request_text << method << " " << path << " HTTP/1.1\r\n"
               << "Host: " << host_ << "\r\n"
               << "Content-Type: application/json\r\n"
               << "Content-Length: " << body.size() << "\r\n"
               << "Connection: close\r\n\r\n"
               << body;
  const std::string payload = request_text.str();

  if (::send(fd, payload.data(), payload.size(), 0) < 0) {
    ::close(fd);
    error = "could not send the request";
    return false;
  }

  std::string raw;
  char buffer[kReadBuffer];
  for (;;) {
    const ssize_t n = ::recv(fd, buffer, sizeof(buffer), 0);
    if (n <= 0) {
      break;
    }
    raw.append(buffer, static_cast<std::size_t>(n));
  }
  ::close(fd);

  if (raw.empty()) {
    error = "the hand API closed the connection without answering";
    return false;
  }

  const auto split = raw.find("\r\n\r\n");
  response = (split == std::string::npos) ? raw : raw.substr(split + 4);

  // A 5xx still carries a JSON body worth reporting, so only the transport is
  // treated as failure here - the caller inspects `success` in the body.
  return true;
}

}  // namespace sequence_executor
